/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package PruebaComponente;

import BotonDeTemperaturas.BotonTemperatura;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;



/**
 *
 * @author socta
 */

/**
 * Aplicación de prueba para demostrar el componente personalizado BotonTemperatura
 * Esta clase muestra cómo usar el botón desde la paleta de componentes de NetBeans
 * y cómo modificar sus propiedades y métodos.
 */
public class CalculadoraTemperaturas extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraTemperaturas
     */
    public CalculadoraTemperaturas() {
        initComponents();
        configurarComponentes();
        conectarBotonPersonalizado();
        
    }
    
     /**
     * Configuración adicional de la interfaz
     */
    private void configurarComponentes() {
        // Configurar el título y propiedades de la ventana
        setTitle("Calculadora de Temperaturas - Demostración Componente Personalizado");
        setLocationRelativeTo(null);
        setResizable(false);
        
        // Configurar estilos de los campos de entrada
        configurarCampoTexto(txtCelsius, "Ingrese temperatura en Celsius");
        configurarCampoTexto(txtFahrenheit, "Ingrese temperatura en Fahrenheit");
        configurarCampoTexto(txtKelvin, "Ingrese temperatura en Kelvin");
        
        // Configurar etiquetas de resultado
        configurarEtiquetaResultado(lblResultadoCelsius);
        configurarEtiquetaResultado(lblResultadoFahrenheit);
        configurarEtiquetaResultado(lblResultadoKelvin);
        
        // Configurar el botón de limpiar
        btnLimpiar.setBackground(new Color(255, 102, 102));
        btnLimpiar.setForeground(Color.WHITE);
        btnLimpiar.setFont(new Font("Arial", Font.BOLD, 12));
        
        // Agregar información sobre el componente personalizado
        lblInfo.setText("<html><center><b>Componente Personalizado:</b> BotonTemperatura<br/>" +
                       "Propiedades modificables: usarColor, modoConversion, colores</center></html>");
    }
    
    /**
     * Conecta el botón personalizado con los campos y etiquetas
     * Aquí es donde se demuestra el uso del componente personalizado
     */
    private void conectarBotonPersonalizado() {
        // DEMOSTRACIÓN: Conectar el botón personalizado con los componentes
        botonTemperatura1.setTxtCelsius(txtCelsius);
        botonTemperatura1.setTxtFahrenheit(txtFahrenheit);
        botonTemperatura1.setTxtKelvin(txtKelvin);
        botonTemperatura1.setLblResultadoCelsius(lblResultadoCelsius);
        botonTemperatura1.setLblResultadoFahrenheit(lblResultadoFahrenheit);
        botonTemperatura1.setLblResultadoKelvin(lblResultadoKelvin);
        
        // DEMOSTRACIÓN: Modificar propiedades del componente personalizado
        botonTemperatura1.setUsarColor(true);
        botonTemperatura1.setModoConversion("Auto");
        botonTemperatura1.setColorNormal(new Color(0, 123, 255));
        botonTemperatura1.setColorSuccess(new Color(40, 167, 69));
        botonTemperatura1.setColorError(new Color(220, 53, 69));
        
        // Configurar tooltip informativo
        botonTemperatura1.setToolTipText("Componente personalizado - Ingrese un valor en cualquier campo y haga clic");
    }
    
    /**
     * Configurar estilo de los campos de texto
     */
    private void configurarCampoTexto(javax.swing.JTextField campo, String placeholder) {
        campo.setFont(new Font("Arial", Font.PLAIN, 14));
        campo.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200), 1),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        // Simular placeholder (en una implementación real usarías una librería o componente personalizado)
        campo.setToolTipText(placeholder);
    }
    
    /**
     * Configurar estilo de las etiquetas de resultado
     */
    private void configurarEtiquetaResultado(javax.swing.JLabel etiqueta) {
        etiqueta.setFont(new Font("Arial", Font.BOLD, 16));
        etiqueta.setForeground(new Color(0, 123, 255));
        etiqueta.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
            BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        etiqueta.setOpaque(true);
        etiqueta.setBackground(new Color(248, 249, 250));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCelsius = new javax.swing.JLabel();
        txtCelsius = new javax.swing.JTextField();
        lblFahrenheit = new javax.swing.JLabel();
        lblKelvin = new javax.swing.JLabel();
        txtFahrenheit = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblTituloResultados = new javax.swing.JLabel();
        lblResultadoCelsius = new javax.swing.JLabel();
        lblResultadoFahrenheit = new javax.swing.JLabel();
        lblResultadoKelvin = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        botonTemperatura1 = new BotonDeTemperaturas.BotonTemperatura();
        btnLimpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Temperaturas - Demostración");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 123, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CALCULADORA DE TEMPERATURAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese Temperatura"));

        lblCelsius.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCelsius.setText("Celsius (°C):");

        txtCelsius.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblFahrenheit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFahrenheit.setText("Fahrenheit (°F):");

        lblKelvin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblKelvin.setText("Kelvin (K):");

        txtFahrenheit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtKelvin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFahrenheit)
                        .addGap(18, 18, 18)
                        .addComponent(txtFahrenheit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCelsius)
                        .addGap(18, 18, 18)
                        .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKelvin)
                        .addGap(18, 18, 18)
                        .addComponent(txtKelvin)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelsius)
                    .addComponent(txtCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFahrenheit)
                    .addComponent(txtFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelvin)
                    .addComponent(txtKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados de Conversión"));

        lblTituloResultados.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblTituloResultados.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloResultados.setText("Los resultados aparecerán aquí después de la conversión");

        lblResultadoCelsius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoCelsius.setText("-- °C");

        lblResultadoFahrenheit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoFahrenheit.setText("-- °F");

        lblResultadoKelvin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultadoKelvin.setText("-- K");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloResultados)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblResultadoKelvin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResultadoFahrenheit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblResultadoCelsius, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloResultados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultadoCelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoFahrenheit)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoKelvin)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        botonTemperatura1.setColorError(new java.awt.Color(220, 53, 69));
        botonTemperatura1.setColorNormal(new java.awt.Color(0, 123, 255));
        botonTemperatura1.setColorSuccess(new java.awt.Color(40, 167, 69));

        btnLimpiar.setText("🗑️ Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonTemperatura1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonTemperatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addGap(21, 21, 21))
        );

        lblInfo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Información del componente personalizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInfo)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
         // DEMOSTRACIÓN: Usar el método resetCampos() del componente personalizado
        botonTemperatura1.resetCampos();
        
        // Mostrar mensaje informativo
        JOptionPane.showMessageDialog(this, 
            "Campos limpiados usando el método resetCampos() del componente personalizado", 
            "Demostración de Método", 
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTemperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTemperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTemperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraTemperaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraTemperaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonDeTemperaturas.BotonTemperatura botonTemperatura1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCelsius;
    private javax.swing.JLabel lblFahrenheit;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKelvin;
    private javax.swing.JLabel lblResultadoCelsius;
    private javax.swing.JLabel lblResultadoFahrenheit;
    private javax.swing.JLabel lblResultadoKelvin;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloResultados;
    private javax.swing.JTextField txtCelsius;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    // End of variables declaration//GEN-END:variables
}
